### ISSUE TITLE
MC群的软妹 铃音（灵摆铃音）

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#10]
目前残余问题：通常召唤成功后的检索失败，已经从卡组中选择卡片了但是没有将卡片送到手牌，另外灵摆区域的抽卡效果不能发动，估计问题应该是灵摆属于怪兽区域还是魔法卡区域这种问题吧

**Comment by SLAPaper** [comment]
灵摆有专门的`LOCATION_PZONE`，应该不是这个问题
现在的灵摆玲音加入了调试代码，你可以注意看一下调试信息

**Comment by SLAPaper** [comment]
截图也可以发在这里的，输入框下面那行字就是介绍这个的

> 通过拖入、选择和从剪贴板粘贴来贴图

看调试信息就是`GetOperationInfo`挂了，而且是不知道为什么挂的，那我就先用类变量弄了
你回头找个类似的卡片我参照一下再试着改

**Comment by diezombies** [comment]
![image](https://cloud.githubusercontent.com/assets/11582097/7002497/4f904828-dc7e-11e4-8f6c-fa50c76ab7af.png)
这个是最新的问题，现在连在当做P卡发动都不行了，无祭品召唤也不行了，估计是哪里发生了什么CRASH？

**Comment by SLAPaper** [comment]
已解决
