### ISSUE TITLE
MC群的妹子 铃音（二重铃音）

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#11]
目前残余问题：卡名没有改变，参照物为次新宇侠，在都二重召唤的情况下次新宇侠名字下面有显示为（元素英雄 新宇侠）而二重铃音没有，不过这个应该关系不大，除非以后节操TF他们又脑洞出什么跟铃音有关的关联卡，可以留到最后再处理

**Comment by SLAPaper** [comment]
![image](https://cloud.githubusercontent.com/assets/7543632/6997250/86219d16-dbe7-11e4-9b9a-27547a9ea937.png)
我看了半天愣是没看出来二重玲音的代码和次新宇侠有什么区别

**Comment by diezombies** [comment]
我也不知道但是这个小新有提示二重铃音没有提示。。。不过无所谓啦
