### ISSUE TITLE
MC群的现充 铃音（超量铃音）

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#13]
目前残余问题：超量召唤成功，但是效果是废纸。话说也就这个铃音要特别标注是什么类型的卡以便于辨认。。。节操你的脑洞真是迷。。。

**Comment by SLAPaper** [comment]
没效果是因为这张卡我没写完。。。

**Comment by SLAPaper** [comment]
抹杀之使徒710444499
No.16 色之支配者54719828

**Comment by SLAPaper** [comment]
> ①去除这张卡一个XYZ素材并以场上一只怪兽为对象才能发动，选择的怪兽从游戏中除外，效果不能发动。

这个效果里面的”效果不能发动“这个效果具体是指什么？
或者说它对应以下哪些情况？
![image](https://cloud.githubusercontent.com/assets/7543632/7059393/f3bbbe66-dea2-11e4-89ea-9625ccf7222e.png)
@diezombies

**Comment by diezombies** [comment]
对应270的不能发动效果
