### ISSUE TITLE
植吧MC群

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#14]
目前残余问题：COST无需支付，一回合一次不被破坏还在，错误代码如下 咦为什么我发不了图片

**Comment by diezombies** [comment]
attemp index a nil value←错误代码

**Comment by SLAPaper** [comment]
如果你把前面的行号也打上的话我会更高兴的

**Comment by diezombies** [comment]
![image](https://cloud.githubusercontent.com/assets/11582097/7002475/d38984a6-dc7d-11e4-83d1-409b60ba3f0c.png)然而这个MC群完全无有改变啊。。。
