### ISSUE TITLE
c284130870 与镰刀尺的契约

### ISSUE THREAD

**Issue by SLAPaper** [SLAPaper/MCGC#16]
又是卡名检索！DZ快去改卡片说明！
@diezombies

**Comment by diezombies** [comment]
前辈这个你就凑合着写吧。。。比起后面的手滑检索铃音这个已经很人道了。。。手滑检索铃音大概能检索六七张的样子更可怕。。。名字带镰刀尺的也就装备镰刀尺和契约镰刀尺而已啦

**Comment by SLAPaper** [comment]
我的意思不是要你把效果改成只契约一张卡，而是指，卡片说明应该和具体实现保持某种程度上的一致
你让我写成只契约两张卡，那就把这两张卡的卡名写到卡面上去，而不是写一个“名字带有镰刀尺”

**Comment by SLAPaper** [comment]
![image](https://cloud.githubusercontent.com/assets/7543632/7163154/1962bc1e-e3cb-11e4-84e6-a30e4211b0d9.png)
@diezombies ……

**Comment by SLAPaper** [comment]
已修复
