### ISSUE TITLE
MC群的软妹 铃音（灵摆铃音）

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#18]
目前残余问题第二弹：只有祭品召唤的时候才能发动检索效果而且还是失败了，如果没看错应该还是GET OPREATION INFO的问题（小学残疾英语水平打错了也不稀奇能理解就行），行数是151，不知道为什么我死活粘贴不上图片所以就手打了，然后摇摆区域依然不能发动效果，但是普召等级下降效果成功，可以用于灵摆召唤

**Comment by SLAPaper** [comment]
我确定我想拆了这个API

**Comment by diezombies** [comment]
算我一个（
我觉得我可以到隔壁群问一下看看有没有大触帮忙解答

**Comment by SLAPaper** [comment]
已解决
