### ISSUE TITLE
MC群的摆渡者 铃音（灵魂铃音）

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#22]
目前残余问题：无，换句话说这张卡是成品~(≧▽≦)/~啦啦啦照搬效果果然成功率很高啊，但是这样显得时髦值很低的说~

**Comment by SLAPaper** [comment]
而我发现这张卡的成功经验对于之前所有卡的问题没有丝毫帮助
因为这张卡的效果里只`SetOperationInfo`了而没有`GetOperationInfo`
在`XXXOperation`函数里面他们直接重新取了一遍对象，而不是从连锁里面取出来
