### ISSUE TITLE
植吧MC群

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#23]
目前残余问题第二弹：发动条件正常，一回合一次不被破坏正常，COST无需发动，送入墓地也没有扣除手卡，应该是有弹错的不过我当时好像忘记截图了orz现在先发着ISS等我中考回来再截一次。。。如果我中考回来之后还有心情和精力的话Orz

**Comment by SLAPaper** [comment]
OK等你回来

**Comment by diezombies** [comment]
看来应该是我当时看错了或者是记错了啥的，结果是没有弹错，这样反而会变得难处理吧大概。。。

**Comment by SLAPaper** [comment]
目前问题：维持cost无需支付
