### ISSUE TITLE
c284130825MC群的现充 手滑

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#43]
目前残余问题：前辈你真的写完了么。。。灵摆区域效果，手卡放回LP回复正常，但是从除外区拿卡是选发效果来着，然后还有就是前辈你把除外写成额外了，而且还没有写sent to hand。。。然后怪兽效果一个都没有成功，特殊召唤不能，拉玲音不能，攻击上升自然也不能。。。

**Comment by SLAPaper** [comment]
（￣へ￣）

**Comment by SLAPaper** [comment]
现在的问题似乎手卡特招和手卡发动时点重叠被覆盖了，是改效果呢还是把两个效果拼成一个呢？

**Comment by SLAPaper** [comment]
最新报告，已经能实现手卡双发了，能双发的版本放在branch: c284130825_alternative里面
仍然存在的问题：
1. 虽然在卡库里面加入了脚本提示文字但是弹选项的时候依然是???
2. 选完选项以后会有个一闪而过的窗口提示“对方选择了？？？”，看了半天也没看到哪里需要对方选

**Comment by SLAPaper** [comment]
将更改合并到branch: master了
