### ISSUE TITLE
284130827 手滑的盘子完成

### ISSUE THREAD

**Issue by SLAPaper** [SLAPaper/MCGC#47]
@diezombies 

手滑的盘子写完了，但是该卡没有录入所以没有测试

但是除此以外还有一些问题出现在卡片定义中：

```
此外，装备怪兽给予对方玩家战斗伤害时，可以根据那个伤害数值发动以下效果：
·低于1000时，自己基本分回复那个伤害的数值
·高于1000低于2000时，自己从卡组抽一张，此卡由卡组装备的场合，这个效果不能发动
·高于2000时，每造成1500伤害，对方随机丢弃一张手卡。此卡由墓地装备的场合，这个效果不能发动
```
1. 这个效果中，“低于1000”是<1000还是<=1000？“高于1000”呢？这里存在区间闭合问题。
2. 根据`这张卡可以从手卡·墓地给自己场上一张名字带有【手滑】的怪兽装备`，这张卡只能从手卡或者墓地装备，那么“此卡由卡组装备的场合”是何用意？

希望尽快解答这些问题，并录入卡片进行测试！

**Comment by diezombies** [comment]
“低于1000”是低于等于一千，高于则是直接高于，然后此卡有卡组装备那个，是我脑残了，当时节操吐槽了我很多次”从卡组装备太挂比了“所以我就把从卡组装备效果去掉了，然而下面那一段我忘记改了orz修改方案为把高于1000低于2000时发动效果的条件去掉，即只要伤害高于1000低于2000就可以发动

**Comment by SLAPaper** [comment]
@diezombies 
写完了，再把把关吧

**Comment by SLAPaper** [comment]
@diezombies 
bug修复了，再测一下吧
