### ISSUE TITLE
大规模测卡行动第二弹

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#71]
84130828罐罐子，攻击力无上升，有报错

84130831普通大小姐，栗子球效果发动时点依然不对，提示发动在受伤之后
84130832幻影节操，32行应该为effect，但是我没看懂为什么不是effect。。。

84130838服主纸睡，检索效果必须要在手上有可以特召的怪兽的场合才能发动
84130840炮灰DZ，变化的等级回合结束没有复原
84130842团员TF六亲不认，无法特召
84130843最终前辈，拉不出来（躺），说好的更改源函数呢（摔）
84130845笨蛋⑨，没有素材的场合依然可以发动效果，并且没有获得对象效果，我怀疑可能是对象的启动/诱发效果类型的原因
84130847失踪者TF缺一个condition
84130848/49大小姐和二小姐都是特召完成但是没有效果
84130850以及打后的全体爆炸， 有报错

**Comment by diezombies** [comment]
多次尝试贴图无果。。。

**Comment by SLAPaper** [comment]
28已修
31已修
32已修
38已修
40已修
42已修
45未发现问题
47已修
48及以后还没开始处理
