### ISSUE TITLE
MC群的群主 纸睡

### ISSUE THREAD

**Issue by diezombies** [SLAPaper/MCGC#8]
目前残余问题：发动顺序不对，另外我改成特召检索通召拉手卡，这样大概会好写一点？等我搞完这个ISSUES我就去继续鼓捣PULL。。。

**Comment by SLAPaper** [comment]
。。。所以你是要我继续调试现在的效果啊还是要改卡片说明重新写效果啊

**Comment by diezombies** [comment]
我的想法是哪个简单前辈你就写哪个吧，如果难度差不多那就重新写吧，现在回头看感觉自己当时写的效果很挂比来着

**Comment by SLAPaper** [comment]
那就重写吧，你去改卡片说明
